### ISSUE TITLE
unable to launch browser -  missing package but unable to find package during cl/cd

### ISSUE THREAD

**Issue by NealWilxite** [rialto-php/puphpeteer#145]
**Describe the bug**
I am unable to run $puppeteer on my kubernetes pod (Apache with Nodejs).  I keep getting a fatal error message starting with:  
```
Fatal error: Uncaught Nesk\Rialto\Exceptions\Node\FatalException: Failed to launch the browser process! /var/www/html/node_modules/puppeteer/.local-chromium/linux-856583/chrome-linux/chrome: error while loading shared libraries: [package name]
```
I then go back to my dockerfile add the package name (after ```apt-get install``` and rebuild the pod.  Rince and repeat.

I have now reached the point where missing package ( libxshmfence.so.1) causes a build pipeline error. Specifically: 
```
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 100
E: Unable to locate package libxshmfence.so.1
E: Couldn't find any package by glob 'libxshmfence.so.1'
E: Couldn't find any package by regex 'libxshmfence.so.1'
Cleaning up file based variables
00:03
ERROR: Job failed: command terminated with exit code 1
```
**Reproducible example**
*index.php*
```
use Nesk\Puphpeteer\Puppeteer;
use Nesk\Rialto\Data\JsFunction;
use Nesk\Rialto\Exceptions\Node;
....

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
....
    $puppeteer = new Puppeteer;
    $browser = $puppeteer->launch([
        'args' => ['--no-sandbox', '--disable-setuid-sandbox'],
    ]);
    $page = $browser->newPage();
    $page->goto('https://example.com');
    // Prints the headers of the response
    var_dump($response->headers());

    // Prints the full HTML contents of the page
    var_dump($page->content());

    $browser->close();
....
```
*package.json*
```
[other code]
 "dependencies": {
    "@nesk/puphpeteer": "^2.0.0",
    "@react-pdf/renderer": "^2.0.16",
    "express": "^4.17.1",
    "file-url": "^3.0.0",
    "nodemon": "^2.0.7",
    "php-express": "^0.0.3",
    "puppeteer": "^8.0.0",
    "react": "^16.14.0"
  },
....
```
*Dockerfile*

```
....
### Install OS tools
RUN apt-get update && apt-get install --yes curl git libmcrypt-dev libreadline-dev libzip-dev

RUN apt-get update -yqq \
    && apt-get install -y --no-install-recommends ca-certificates fonts-liberation gconf-service libappindicator1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libdrm2 libexpat1 libfontconfig1 libgbm1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libjpeg62 libmagickwand-dev libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libssl-dev libstdc++6 libx11-6 libx11-dev libx11-xcb1 libxcb-dri3-0 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxml2-dev libxrandr2 libxrender1 libxss1 libaio1 libaio-dev libxtst6 lsb-release xdg-utils zlib1g-dev wget \
    && pecl install imagick mcrypt-1.0.2 \
    && docker-php-ext-install sockets \
	&& docker-php-ext-enable imagick sockets
....
```

**Expected behavior**
1. Start a headless Chrome (sans Sandbox)
2. Opens a tab
3. Loads "https://example.com"
4. . shows headers of response and html contents on page
5. Close browser

**Generated logs**
[monolog-log_2021-07-16.txt](https://github.com/rialto-php/puphpeteer/files/6832794/monolog-log_2021-07-16.txt)

**Screenshots**
![screenshot_2021-07-16_19-12-16_o](https://user-images.githubusercontent.com/54668805/125995604-1a1a11d3-f157-40c7-b9a2-003c265a5289.png)

**Environment (please complete the following information):**
 - OS: CentOS Linux 7 (Core) amd64
 - Docker (Kubernetes): 19.3.12
 - Node version: v14.17.2
 - PHP version: 7.4.19

My Node package manager is:
 - [x] NPM 6.14.13
 - [ ] Yarn (specify the version)
 - [ ] Other (specify the name and version)

**Additional context**  
*Fatal error text*
```
Fatal error: Uncaught Nesk\Rialto\Exceptions\Node\FatalException: Failed to launch the browser process! /var/www/html/node_modules/puppeteer/.local-chromium/linux-856583/chrome-linux/chrome: error while loading shared libraries: libxshmfence.so.1: cannot open shared object file: No such file or directory TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md in /var/www/html/vendor/nesk/rialto/src/ProcessSupervisor.php:307 Stack trace: #0 /var/www/html/vendor/nesk/rialto/src/ProcessSupervisor.php(387): Nesk\Rialto\ProcessSupervisor->checkProcessStatus() #1 /var/www/html/vendor/nesk/rialto/src/Traits/CommunicatesWithProcessSupervisor.php(84): Nesk\Rialto\ProcessSupervisor->executeInstruction(Object(Nesk\Rialto\Instruction)) #2 /var/www/html/vendor/nesk/rialto/src/Traits/CommunicatesWithProcessSupervisor.php(100): Nesk\Rialto\AbstractEntryPoint->proxyAction('call', 'launch', Array) #3 /var/www/html/public/index.php(79): Nesk\Rialto\AbstractEntryPoint->__call('launch', Array) #4 {main} in /var/www/html/vendor/nesk/rialto/src/ProcessSupervisor.php on line 307
```

**Comment by NealWilxite** [comment]
I've decided to go a different route for the api (using Golang)
